#!/bin/bash
echo -e "BUILD\t: BEGIN `date`"

mkdir -p src

echo -e "BUILD\t: copying files from scv-static"
cp -rv node_modules/@sc-voice/scv-static/components/* components
cp -rv node_modules/@sc-voice/scv-static/static/* static
cp -rv node_modules/@sc-voice/scv-static/plugins/* plugins
cp -rv node_modules/@sc-voice/scv-static/pages/* pages
cp -rv node_modules/@sc-voice/scv-static/src/* src
cp -rv node_modules/@sc-voice/scv-static/store/* store
cp -v node_modules/@sc-voice/scv-static/index* .

echo -e "BUILD\t: END `date`"
